### PR TITLE
Include Test data

### LINKED ISSUE #4: Test workflow execution with a test data
Add some small samples to run the full workflow. As input the mapped reads can be used and the outputs are two list of genes and some visualisations. The test data should not exceed 20 MB.

This helps to

- test the workflow and if all steps are running properly
- configure and set-up own samples based on the provided test samples

The following should be added:

- [x] at least two samples with mapped reads in BAM format; the same genomic region should be used in all samples
- [x] cell type annotations for at least two cell types from the samples
- [x] the relevant subset of the genome annotation
- [x] the samples table `samples.tsv`
- [x] the configuration file `config.yaml`

### PR DESCRIPTION
**Pull request by dominikburri**
## Description

Include test data to perform CI on actual small samples. Included as extension of the github actions already implemented.

Fixes #4

### CODE REVIEW

**Review by AngryMaciek — CHANGES_REQUESTED** [review]
I think that you should not include a separate `testdata.yml` workflow in the CI in your current setup. Please notice that you already have a `ci.yml` file which spawns both cell type/cell state tests. **And all that seems to be repeated in the new CI workflow too**.
If I were you I would stick to the `ci.yml` and just add the new steps (commands for local run on test data) at the end of both respective CI jobs (cell type / cell state). Then you also would not need to adjust the README shield for CI, as the whole thing would be tested via one main workflow, written in `ci.yml`. And this is the one that is hooked up to the shield.

**Comment by AngryMaciek** [comment]
> I think that you should not include a separate `testdata.yml` workflow in the CI in your current setup. Please notice that you already have a `ci.yml` file which spawns both cell type/cell state tests. **And all that seems to be repeated in the new CI workflow too**. If I were you I would stick to the `ci.yml` and just add the new steps (commands for local run on test data) at the end of both respective CI jobs (cell type / cell state). Then you also would not need to adjust the README shield for CI, as the whole thing would be tested via one main workflow, written in `ci.yml`. And this is the one that is hooked up to the shield.

Alternatively you can refactor all your CI tests to separate CI workflows. You would then have: `dryrun.yml`, `integration.yml`, `dag.yml`. All these would be run as separate workflows in parallel but each of these files would be a 1-command CI job, looks silly IMO. I think it makes more sense to aggregate them as you have it now.

**Comment by dominikburri** [comment]
> I think that you should not include a separate `testdata.yml` workflow in the CI in your current setup. Please notice that you already have a `ci.yml` file which spawns both cell type/cell state tests. **And all that seems to be repeated in the new CI workflow too**. If I were you I would stick to the `ci.yml` and just add the new steps (commands for local run on test data) at the end of both respective CI jobs (cell type / cell state). Then you also would not need to adjust the README shield for CI, as the whole thing would be tested via one main workflow, written in `ci.yml`. And this is the one that is hooked up to the shield.

Thanks for the clarifications. I think, having one `ci.yml` totally makes sense. I will include dry-runs and local runs for the test data because it is in its own `.test/integration` directory (compared to `.test/integration-dry`).

**Review by AngryMaciek — APPROVED** [review]
OK, looks good!

**Pull request merged**
